# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177d51489037cd3cf18eb89cfec372287c9c92e56cbb19586959ec6d8f03b871acea775ff9b23cc3aa0b2547e4ab7602c41e6e07d673659adcb6d0d807ba6787

test:
  secret_key_base: f99c30cbdecb633691878ec16221a0e0b163f81aba6ee57ab93a98bc39a6f2a2c78e47a210b8eb433ba03605234feca03f1b23ee2b2557aadbbc21718795f082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
